# MyAmazingApp - Production Environment
#
# https://my.amazing_app.be
#     /var/www/amazing
#     pgsql: host=1.2.3.4 port=5438 dbname=amazing username=christophe
#
# <yellow>Backend:</yellow> PHP 8.5
# <green>Note:</green>    Part of TremendousApp.
#
# <bg-red>  CRITICAL  </bg-red> - This is a production server!
# <bg-yellow>    INFO    </bg-yellow> - Database is <green>PostgreSQL</green>
Host MyAmazingApp_PROD
    Hostname 1.2.3.4
    User usr_app_prod

# MyAmazingApp - Tests Environment
#
# https://my.tests_amazing_app.be
#     /var/www/tests_amazing
#     pgsql: host=1.2.3.4 port=5438 dbname=amazing_newx username=christophe
#
# <yellow>Backend:</yellow> PHP 8.3
# <green>Note:</green> This is the TESTS environment
#
# <bg-yellow>    INFO    </bg-yellow> - Database is <green>PostgreSQL</green>
Host MyAmazingApp_TEST
    Hostname 6.7.8.9
    User usr_app_test

Host YourAmazingApp
    Hostname 1.2.3.4
    User you
